### ISSUE TITLE
Does knative serving simplify app deployment?

### ISSUE THREAD

**Issue by mikegehard** [initialcapacity/freshcloud#3]
https://knative.dev/docs/serving/

Currently `freshctl` uses  `Deployment`, `Service` and `Ingress` manifests. Could knative serving simplify that?

**Comment by jmcdice** [comment]
That is interesting. There are some things I like in this model but also some things I don't like as much. I assume that the only piece we're interested in here is the deployment (not container building and pushing to dockerhub/harbor). This requires knative to be installed, uses a single load-balancer per application and we would need to figure out how to get cert-manager to create/manage application certs. Mostly thought, I think of freshctl as a learning tool and adding knative to the mix sort of abstracts the core concepts (deployment, service and ingress). It does add some advanced functionality though (autoscaling, snapshots, blue-green deployments, etc) which could be a nice 201 exercise.

**Comment by mikegehard** [comment]
Agreed…it does abstract away a bunch of lower level k8s concepts.

And yeah just the serving part is what I was thinking.
